"""Vertical stacking validation.

Every column generated by Agent 3 spans from the lowest level to the
highest. Most floor plates are identical (typical office tower), but
some buildings have setbacks: the upper floor plate is smaller than
the lower. A column standing in the upper-floor "void" needs a
transfer structure to bring its load down — that's an engineering
decision, not something the generator can resolve. We surface it as a
warning instead of silently ignoring it.

This module is read-only: it never moves, removes, or otherwise
modifies columns. It just emits warnings the orchestrator forwards
into ``SchemeMetrics.warnings``.
"""

from __future__ import annotations

from shapely.geometry import Point, Polygon

from packages.engine.column_generator.constants import EDGE_TOLERANCE


def validate_stacking(columns: list[dict], levels: list[dict]) -> list[str]:
    """Return warning strings for columns that don't sit inside the
    floor plate of every level they span.

    Levels that have no ``planBoundary`` are skipped — we don't have
    enough information to assert a stacking failure there.
    """
    if not columns or not levels:
        return []

    levels_sorted = sorted(levels, key=lambda l: l.get("elevation", 0.0))
    level_index = {lvl["id"]: i for i, lvl in enumerate(levels_sorted)}

    polys: dict[str, Polygon | None] = {}
    for lvl in levels_sorted:
        polys[lvl["id"]] = _polygon_for_level(lvl)

    warnings: list[str] = []
    for col in columns:
        s = level_index.get(col.get("start_level"))
        e = level_index.get(col.get("end_level"))
        if s is None or e is None:
            continue
        lo, hi = (s, e) if s <= e else (e, s)

        for idx in range(lo, hi + 1):
            lvl = levels_sorted[idx]
            poly = polys.get(lvl["id"])
            if poly is None:
                continue
            pt = Point(col["x"], col["y"])
            if poly.covers(pt) or poly.distance(pt) <= EDGE_TOLERANCE:
                continue
            warnings.append(
                f"Column {col.get('id', '?')} not inside floor plate at level "
                f"{lvl['id']} — transfer structure may be required."
            )
            break  # one warning per column is enough

    return warnings


def _polygon_for_level(level: dict) -> Polygon | None:
    boundary = level.get("planBoundary")
    if not boundary or len(boundary) < 3:
        return None
    pts: list[tuple[float, float]] = []
    for p in boundary:
        if isinstance(p, dict):
            pts.append((float(p["x"]), float(p["y"])))
        else:
            pts.append((float(p[0]), float(p[1])))
    if len(pts) >= 4 and pts[0] == pts[-1]:
        pts = pts[:-1]
    if len(pts) < 3:
        return None
    try:
        poly = Polygon(pts)
        if not poly.is_valid:
            poly = poly.buffer(0)
        return poly if not poly.is_empty else None
    except Exception:
        return None


__all__ = ["validate_stacking"]
